x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

# 1. Объявляем сеть
networks:
  judge0-network:
    driver: bridge

services:
  judge0-server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks: # 2. Подключаем к сети
      - judge0-network
    <<: *default-logging
    restart: always

  judge0-worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks: # 2. Подключаем к сети
      - judge0-network
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks: # 2. Подключаем к сети
      - judge0-network
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: .env
    networks: # 2. Подключаем к сети
      - judge0-network
    <<: *default-logging
    restart: always

  task-checker-db:
    image: postgres:16.2
    env_file: .env
    environment:
      - POSTGRES_DB=${TASK_CHECKER_DB_NAME:-task_checker}
      - POSTGRES_USER=${TASK_CHECKER_DB_USER:-task_checker}
      - POSTGRES_PASSWORD=${TASK_CHECKER_DB_PASSWORD:-task_checker_password}
    volumes:
      - task-checker-postgres-data:/var/lib/postgresql/data/
    networks:
      - judge0-network
    <<: *default-logging
    restart: always

  task-checker:
    build:
      context: ./task_checker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - judge0-server
      - task-checker-db
    networks: # 2. Подключаем к сети
      - judge0-network
    <<: *default-logging
    restart: always

volumes:
  postgres-data:
  task-checker-postgres-data: